In [1]:
import numpy as np

data=np.load('data.npy')
target=np.load('target.npy')


In [2]:
from keras.models import Sequential
from keras.layers import Dense,Activation,Flatten
from keras.layers import Conv2D,MaxPooling2D,Dropout,BatchNormalization

model=Sequential()

model.add(Conv2D(56,(3,3),input_shape=data.shape[1:],kernel_initializer = 'orthogonal')) 
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))


model.add(Conv2D(28,(3,3),kernel_initializer = 'orthogonal'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))


model.add(Conv2D(14,(3,3),kernel_initializer = 'orthogonal'))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dropout(0.5))
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64,activation='relu'))
model.add(Dense(2,activation='softmax'))


model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 48, 48, 56)        560       
                                                                 
 batch_normalization (BatchN  (None, 48, 48, 56)       224       
 ormalization)                                                   
                                                                 
 activation (Activation)     (None, 48, 48, 56)        0         
                                                                 
 max_pooling2d (MaxPooling2D  (None, 24, 24, 56)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 22, 22, 28)        14140     
                                                                 
 batch_normalization_1 (Batc  (None, 22, 22, 28)       1

In [3]:
model.load_weights('cat and dog training.h5')

In [4]:
import os
import cv2
import numpy as np

test_path='test image'

img_names=os.listdir(test_path)
category_dict={0:'cat',1:'dog'}

for img_name in img_names:
    img=cv2.imread(os.path.join(test_path,img_name))
    h,w=img.shape[0:2]

    #preprocessing (As done for the training images)
    test_img=cv2.resize(img,(50,50))
    test_img=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
    test_img=test_img/255
    test_img=test_img.reshape(1,50,50,1)
    
    results=model.predict(test_img)
    label=np.argmax(results,axis=1)[0]
    acc=int(np.max(results,axis=1)[0]*100)
    
    print(results,label,category_dict[label],acc)
    
    img[0:50,0:w]=[0,255,0]
    cv2.putText(img,category_dict[label],(20,40),cv2.FONT_HERSHEY_SIMPLEX,1.5,(255,255,255),2)
    cv2.putText(img,str(acc)+'%',(120,40),cv2.FONT_HERSHEY_SIMPLEX,1.5,(255,255,255),2)
    
    cv2.imshow('LIVE',img)
    k=cv2.waitKey(1000)
    if(k==27):
        break
cv2.destroyAllWindows()

1/1 [==============================] - 3s 3s/step
[[0.05611232 0.94388765]] 1 dog 94
1/1 [==============================] - 0s 22ms/step
[[0.08454908 0.91545093]] 1 dog 91
1/1 [==============================] - 0s 22ms/step
[[0.04257771 0.9574223 ]] 1 dog 95
1/1 [==============================] - 0s 22ms/step
[[0.04560406 0.95439595]] 1 dog 95
1/1 [==============================] - 0s 29ms/step
[[0.29208404 0.70791596]] 1 dog 70
1/1 [==============================] - 0s 18ms/step
[[0.22254398 0.7774561 ]] 1 dog 77
1/1 [==============================] - 0s 16ms/step
[[0.02673297 0.973267  ]] 1 dog 97
1/1 [==============================] - 0s 21ms/step
[[0.11977147 0.8802285 ]] 1 dog 88
1/1 [==============================] - 0s 16ms/step
[[0.00408823 0.99591184]] 1 dog 99
1/1 [==============================] - 0s 16ms/step
[[0.02763383 0.9723662 ]] 1 dog 97
1/1 [==============================] - 0s 21ms/step
[[0.67514265 0.32485735]] 0 cat 67
1/1 [==============================] - 0s 18m